### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by doroved** [ItsEeleeya/tauri-plugin-macos-haptics#1]
```
12:06:09 AM [vite] Internal server error: Failed to resolve import "tauri-plugin-macos-haptics-api" from "src/routes/index.tsx?pick=default&pick=$css". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/src/routes/index.tsx?pick=default&pick=$css:6:7
  5  |  var _tmpl$ = /* @__PURE__ */ _$template(`<div data-tauri-drag-region class="user-select-none fixed left-0 right-0 top-0 flex h-11 items-center justify-end"><button type=button class="btn btn-xs btn-ghost mr-3 mt-0.5">Star on Github!`), _tmpl$2 = /* @__PURE__ */ _$template(`<div class="flex min-h-screen w-full flex-col items-center justify-center gap-6 text-center"><h1 class="text-center text-4xl font-semibold ">Tauri macOS Haptics</h1><input type=checkbox class=toggle>`);
  6  |  import { open } from "@tauri-apps/plugin-shell";
  7  |  import { HapticFeedbackPattern, perform, PerformanceTime } from "tauri-plugin-macos-haptics-api";
     |                                                                   ^
  8  |  import StepSlider from "~/components/step-slider";
  9  |  import Github from "~/icons/github";
      at TransformPluginContext._formatError (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49193:41)
      at TransformPluginContext.error (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49188:16)
      at normalizeUrl (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:63984:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64116:39
      at async Promise.all (index 5)
      at async TransformPluginContext.transform (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64043:7)
      at async PluginContainer.transform (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49034:18)
      at async loadAndTransform (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:51867:27)
12:06:09 AM [vite] Pre-transform error: Failed to resolve import "tauri-plugin-macos-haptics-api" from "src/components/step-slider.tsx". Does the file exist?
12:06:09 AM [vite] Internal server error: Failed to resolve import "tauri-plugin-macos-haptics-api" from "src/routes/index.tsx?pick=default&pick=$css". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/src/routes/index.tsx?pick=default&pick=$css:6:7
  9  |  var _tmpl$ = /* @__PURE__ */ _$template(`<div data-tauri-drag-region class="user-select-none fixed left-0 right-0 top-0 flex h-11 items-center justify-end"><button type=button class="btn btn-xs btn-ghost mr-3 mt-0.5"><!$><!/>Star on Github!`), _tmpl$2 = /* @__PURE__ */ _$template(`<div class="flex min-h-screen w-full flex-col items-center justify-center gap-6 text-center"><h1 class="text-center text-4xl font-semibold ">Tauri macOS Haptics</h1><!$><!/><input type=checkbox class=toggle>`);
  10 |  import { open } from "@tauri-apps/plugin-shell";
  11 |  import { HapticFeedbackPattern, perform, PerformanceTime } from "tauri-plugin-macos-haptics-api";
     |                                                                   ^
  12 |  import StepSlider from "~/components/step-slider";
  13 |  import Github from "~/icons/github";
      at TransformPluginContext._formatError (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49193:41)
      at TransformPluginContext.error (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49188:16)
      at normalizeUrl (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:63984:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64116:39
      at async Promise.all (index 9)
      at async TransformPluginContext.transform (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64043:7)
      at async PluginContainer.transform (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49034:18)
      at async loadAndTransform (file:///Users/doroved/Development/TESTS/tauri-plugin-macos-haptics/example/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:51867:27)
12:06:09 AM [vite] Pre-transform error: Failed to resolve import "tauri-plugin-macos-haptics-api" from "src/components/step-slider.tsx". Does the file exist?
^C ELIFECYCLE  Command failed.
error: script "tauri" exited with code 130
```

**Comment by ItsEeleeya** [comment]
Did you try running `pnpm/npm install` on the project root first?
I ran into the same problem when I didn't have the JS package built.
